### ISSUE TITLE
gunicorn update from 19.x.x to 20.x.x results in 503 Deadline Exceeded

### ISSUE THREAD

**Issue by tjg37** [googleapis/python-tasks#25] opened 2020-05-21 13:12 UTC
#### Environment details

  - OS type and version:
  - Python version: 3.6
  - pip version: 10.0.1
  - `google-cloud-tasks` version: 1.5.0
  - Django: 3.0.5 
  - Gunicorn: 20.0.0

#### Steps to reproduce

  1. Deploy Django server to GAE Flex environment with gunicorn version 20.0.0
  2. Attempt to queue a cloud task
  3. Receive an error `google.api_core.exceptions.ServiceUnavailable: 503 Deadline Exceeded` and the task is not created. 
  4. If we revert the gunicorn version to 19.9.0 and redeploy, we are able to successfully queue a task. 

#### Code example

```python
    from google.cloud import tasks_v2
    project = getattr(settings, ‘GCLOUD_PROJECT’)
    location = getattr(settings, ‘LOCATION’)
    client = tasks_v2.CloudTasksClient()
    parent = client.queue_path(project, location, queue)
    task = {
        ‘app_engine_http_request’: { # Specify the type of request.
            ‘http_method’: ‘POST’,
            ‘relative_uri’: <>
            ‘headers’: {
                ‘Content-Type’: ‘application/json’
            }
        }
    }
    response = client.create_task(parent, task)
```

#### Stack trace
```
Traceback (most recent call last): File "/home/vmagent/app/cache/views/tasks/cron_task_viewset.py", line 647, in cache object_processing_uri=PATH_QUEUE_TASKS + "cache/", File "/home/vmagent/app/utils/tasks/__init__.py", line 148, in chunk task_generator.queue_task() File "/home/vmagent/app/utils/tasks/__init__.py", line 90, in queue_task response = self.client.create_task(self.parent, task) File "/env/lib/python3.6/site-packages/google/cloud/tasks_v2/gapic/cloud_tasks_client.py", line 1508, in create_task request, retry=retry, timeout=timeout, metadata=metadata File "/env/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__ return wrapped_func(*args, **kwargs) File "/env/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func on_error=on_error, File "/env/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target return target() File "/env/lib/python3.6/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout return func(*args, **kwargs) File "/env/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable six.raise_from(exceptions.from_grpc_error(exc), exc) File "<string>", line 3, in raise_from google.api_core.exceptions.ServiceUnavailable: 503 Deadline Exceeded
```

There appear to be breaking changes in gunicorn 20.x.x and `google-cloud-tasks` needs to be updated accordingly. 

I hope that the above is helpful. 

Thanks!

**Comment by mikeweng** [comment] 2020-09-02 07:46
@tjg37 Are you using gevent with gunicorn?

Tried gunicorn 19.9.0, still facing the same issue. Seeing the transport is grpc, I've patched with 
```
import grpc.experimental.gevent as grpc_gevent
grpc_gevent.init_gevent()
```
from https://github.com/grpc/grpc/issues/4629#issuecomment-376962677 and addressed the issue.

**Comment by tjg37** [comment] 2020-09-02 08:56
@mikeweng We're using eventlet with gunicorn.

**Comment by mikeweng** [comment] 2020-09-02 09:09
Saw a PR (https://github.com/grpc/grpc/pull/22062) for eventlet but got closed.

**Comment by tjg37** [comment] 2020-09-02 09:22
Yeah, it looks like the PR (https://github.com/grpc/grpc/pull/22062) was closed when the PR (https://github.com/grpc/grpc/pull/22270) was opened. Although PR (https://github.com/grpc/grpc/pull/22270) looks like it's just related to improving testing. 

In our case, we are only receiving the `google.api_core.exceptions.ServiceUnavailable: 503 Deadline Exceeded` error when updating  gunicorn from 19.x.x to 20.x.x. To get around this issue, we're currently using gunicorn 19.9.0, but we're unable to upgrade to gunicorn 20.x.x.

**Comment by busunkim96** [comment] 2020-11-06 04:43
Hi,


I know it's been a while since this was filed, but if anyone following is able to provide a gRPC log that would be helpful for further debugging.

**Please redact sensitive information like auth tokens and project IDs before pasting logs here.** If you are a Googler, feel free to add on to the internal copy of this issue (157230834) instead.

```
export GRPC_VERBOSITY=DEBUG
export GRPC_TRACE=all
```

According to this [stackoverflow post](https://stackoverflow.com/questions/62992762/errorgrpc-plugin-wrappingauthmetadataplugincallback-raised-exception-gunico) gRPC Python has experimental support for `gevent`. It does not work well with `eventlet`. As noted above there was a PR earlier this year to add support for `eventlet` but it appears to have gone stale.

I'm not sure if this changes anything for this issue, but there is an [async client](https://github.com/googleapis/python-tasks/blob/master/google/cloud/tasks_v2/services/cloud_tasks/async_client.py) in the 2.0.0 of this library.

On a related note - has anyone reproduced this on the 2.x.x releases?

**Comment by kujbol** [comment] 2020-11-09 16:29
@tjg37 
As far I remember on Pre 20.x.x there was a problem with auto patching eventlet, 
https://docs.gunicorn.org/en/stable/news.html?highlight=eventlet#id6

your app might be not using eventlet at all, and that is why it's working on 19.9.0, 
I checked and you will get the same error on 19.9.0 when you will manually patch eventlet for example with that gunicorn_conf.py file 

```
from eventlet import monkey_patch

workers = 4
worker_class = 'eventlet'
worker_connections = 100

def post_fork(server, worker):
    monkey_patch()
    worker.log.info("Made Psycopg2 Green")
```

**Comment by tjg37** [comment] 2020-11-10 13:14
Thanks for all the helpful comments. I'd like to add some additional information to supplement my initial comment:

Using  `gunicorn==20.0.0` and an entry point of `entrypoint: gunicorn -b :$PORT -c gunicorn.conf.py config.wsgi` in app.yaml without eventlet,  I didn't receive the errors. That is, all the queued tasked completed successfully.

Similarly, when using `gunicorn[eventlet]==19.9.0` and an entry point of `entrypoint: gunicorn -b :$PORT -c gunicorn.conf.py -k eventlet config.wsgi` in app.yaml with eventlet,  I also didn't receive the errors. That is to say that all the queued tasked completed successfully.

However, trying again with `gunicorn[eventlet]==20.0.0` and entry point of `entrypoint: gunicorn -b :$PORT -c gunicorn.conf.py -k eventlet config.wsgi` in app.yaml, I ran into the same issue:

```
503 Deadline Exceeded

Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/env/lib/python3.6/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/env/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

status = StatusCode.UNAVAILABLE

details = "Deadline Exceeded"

debug_error_string = "{"created":"@1604966029.254618113","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":14}"

>

503 Deadline Exceeded Traceback (most recent call last): File "/env/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable return callable_(*args, **kwargs) File "/env/lib/python3.6/site-packages/grpc/_channel.py", line 923, in __call__ return _end_unary_response_blocking(state, call, False, None) File "/env/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking raise _InactiveRpcError(state) grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "Deadline Exceeded" debug_error_string = "{"created":"@1604966029.254618113","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":14}" > The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/vmagent/app/vouchers/views/tasks/cron_task_viewset.py", line 647, in cache_mealplans object_processing_uri=PATH_CONNECT_QUEUE_TASKS + "cache_mealplan/", File "/home/vmagent/app/utils/tasks/__init__.py", line 148, in chunk task_generator.queue_task() File "/home/vmagent/app/utils/tasks/__init__.py", line 90, in queue_task response = self.client.create_task(self.parent, task) File "/env/lib/python3.6/site-packages/google/cloud/tasks_v2/gapic/cloud_tasks_client.py", line 1508, in create_task request, retry=retry, timeout=timeout, metadata=metadata File "/env/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__ return wrapped_func(*args, **kwargs) File "/env/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func on_error=on_error, File "/env/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target return target() File "/env/lib/python3.6/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout return func(*args, **kwargs) File "/env/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable six.raise_from(exceptions.from_grpc_error(exc), exc) File "<string>", line 3, in raise_from google.api_core.exceptions.ServiceUnavailable: 
```

I also tried using the patch as suggested by @kujbol by adding the monkey_patch to the gunicorn_conf.py file but received the same `503 Deadline Exceeded` error.

It would appear that using eventlet is the source of the issue. Is the solution to not use eventlet if possible?

**Comment by busunkim96** [comment] 2020-12-09 17:29
@tjg37 Yep, I confirmed with @lidizheng from gRPC that `eventlet` is not supported by `gRPC`.

> From the gRPC Python perspective, we only support several i/o platforms: native (default), gevent, or asyncio. The eventlet support had some progress last year, but it is not on our road map. **The RPC timeout is due to gRPC Core unable to interact with eventlet's polling engine**. Welcome to tryout other i/o platforms.
> 
> From the performance perspective, gRPC uses C extensions that encapsulated the networking, security, codec, load-balancing logic. It's usually out-performing pure Python networking libraries in terms of latency and throughput.

As there is nothing else we can do in this client library side I'm going to go ahead and close this issue.

**Closed by busunkim96** 2020-12-09 17:29 UTC
Labels: :rotating_light:, api: cloudtasks, priority: p2, type: bug

**Comment by tjg37** [comment] 2020-12-09 17:32
@busunkim96 Thanks for the helpful information.
